# Generated by Django 5.0.4 on 2024-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('correo_electronico', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.PositiveIntegerField()),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('bibliotecario', 'Bibliotecario'), ('administrador', 'Administrador'), ('usuario_regular', 'Usuario Regular')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
    ]
